### ISSUE TITLE
svc_interface.sysl does not handle untyped `return ok` response

### ISSUE THREAD

**Issue by ghost** [anz-bank/sysl-go#104]
given an endpoint like this:
```
foo:
    /orders:
        POST:
            return error <: Error
            return ok
```

the svc_client.sysl transform will create a func `PostOrders(ctx context.Context, req *PostOrdersRequest) (*http.Header, error)` however the svc_interface.sysl does not handle the untyped ok and it generates `PostOrders(ctx context.Context, req *PostOrdersRequest) error` instead. This ends up causing a compile time failure trying to initialisae the service interface.

**Comment by springwiz** [comment]
@anz-gordonj7 "return ok" should work, it generates the following code in serviceinterface.go.
GetEmptyokList            func(ctx context.Context, req *GetEmptyokListRequest, client GetEmptyokListClient) error
The code also compiles, there are working examples in simple.sysl.
https://github.com/anz-bank/sysl-go/blob/master/codegen/testdata/simple/simple.sysl.
Please pickup the latest version of Sysl-Go.

**Comment by ghost** [comment]
@springwiz I must not have been clear enough, sorry.

svc_client.sysl generates the func (in the `service` interface) -> `PostOrders(ctx context.Context, req *PostOrdersRequest) (*http.Header, error)`

svc_serviceinterface.sysl generates the func -> `PostOrders(ctx context.Context, req *PostOrdersRequest) error`

Notice how the 2 signatures are different? They must be the same or else the generated code wont compile.

**Comment by ghost** [comment]
@springwiz the testcase for simple.sysl is an endpoint that calls another endpoint which returns `ok`
