### ISSUE TITLE
Need to be able to pull headers out of the restlib response

### ISSUE THREAD

**Issue by ghost** [anz-bank/sysl-go#105]
Some downstream systems send response headers as well as a body. We want to be able to markup the sysl to say which header fields are wanted as well as the body

**Comment by ChloePlanet** [comment]
There's a workaround to solve this issue now.

**Comment by ghost** [comment]
@ChloePlanet which is?

**Comment by suipinglu** [comment]
Hi Andrew and the team,

Thanks for the confirmation this afternoon, just want to put in more info for the team to reference. :) 

So, one of the downstream will response error 400 for different scenarios for business:
```
400 - Bad Request
{
  "message": [
    {
      "text": "10001 - Business Error AAA",
      "type": "error"
    }
  ]
}
```
```
400 - Bad Request
{
  "message": [
    {
      "text": "10002 - Business Error BBB",
      "type": "error"
    }
  ]
}
```
What we need to achieve here, is to get the error body and drill down into the "text" part to see what is the actual cause for this 400 error.

Cheers,
Ping

**Comment by tiagralee** [comment]
Hi @suipinglu , I'm running `bah-bff` to test this issue, could you help give me an example endpoint to reproduce the 400 response?
