### ISSUE TITLE
codegen transforms don't handle sysl "double" type

### ISSUE THREAD

**Issue by ghost** [anz-bank/sysl-go#107]
the sysl "double" type gets output directly to the types.go file (or any of them) without a typedef. 
`type double float64` needs to be generated

**Comment by tiagralee** [comment]
@anz-gordonj7 I had a look in sysl transformation, the type mapping are as below:
```
          "DECIMAL" => "double"
          "INT" => "int64"
          "FLOAT" => "float64"
```
I did a test, the current transform is from:
```
    !type TestDoubleType:
        price <: decimal
        priceFloat <: float
```
to 
```
type TestDoubleType struct {
	Price       double  `json:"price"`
	PriceFloat  float64 `json:"priceFloat"`
}
```
Can you use `decimal` or `float` instead or we need to add a rule for double?
Looks like `double` is not a sysl type from the intellisense.
![image](https://user-images.githubusercontent.com/5410464/82269920-6f61cf00-99b6-11ea-96f2-bd291a8dcc01.png)

**Comment by ghost** [comment]
yeah, `double` is not a sysl type, so I guess the actual problem is the code that generated the sysl needs to be fixed, lets close this
