### ISSUE TITLE
Enforce JSON required fields when decoding

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl-go#108]
`sysl-go` automatically decodes an incoming request body in the following manner:
```go
decoder := json.NewDecoder(r.Body)
decodeErr := decoder.Decode(&req.Request)
if decodeErr != nil {
    common.HandleError(ctx, w, common.BadRequestError, "Error reading request body", decodeErr, s.genCallback.MapError)
    return
}
```

Given the following example describes a request body with required `name` and `dateOfBirth` values and an optional `nickname` value:
```go
type RegisterRequest struct {
    Name         string            `json:"name"`
    Nickname     *string           `json:"nickname"`
    DateOfBirth  date.Date         `json:"dateOfBirth"`
}
```

If the client passes an empty `json` object: `{}`, the `json` decoder will construct the following equivalent object:
```go
RegisterRequest{
    Name: "",
    Nickname: nil,
    DateOfBirth: date.Date{},
}
```

The decoded value is then passed to the request handler to process. In some instances it's sufficient to check for the default value of a field and reject it, however in some instances it's necessary to differentiate between a missing or `null` value and the default value. In the example above, the default `date.Date` object is equivalent to `1970-01-01`, making it impossible to know if the object included a `dateOfBirth` value or not. Ideally, an error should be encountered if a `json` object does not contain a required value.

The `json` decoder has poor support for checking required values in decoding, however [this](https://stackoverflow.com/a/39134081) approach describes how it can be done. The basic approach involves generating an equivalent type with fields of pointer types and manually checking their nil values:

```go
type registerRequest_ struct {
    Name        *string    `json:"name"`
    Nickname    *string   `json:"nickname"`
    DateOfBirth *date.Date `json:"dateOfBirth"`
}

func (target *RegisterRequest) UnmarshalJSON(data []byte) error {
    inner := registerRequest_{}
    err := json.Unmarshal(data, &inner)
    if err != nil {
        return err
    }
    if inner.Name == nil {
        return errors.New("name cannot be nil")
    }
    if inner.DateOfBirth == nil {
        return errors.New("dateOfBirth cannot be nil")
    }
    *target = RegisterRequest{
        Name:        *inner.Name,
        Nickname:    inner.Nickname,
        DateOfBirth: *inner.DateOfBirth,
    }
    return nil
}
```

**Comment by andrewemeryanz** [comment]
Further work required.

**Comment by andrewemeryanz** [comment]
Further work required. Below is an example of the generated code:

```go
type GetStuffListRequest struct {
	Dt *convert.JSONTime
	St *string
	Bt *bool
	It int64
}

func (r *GetStuffListRequest) UnmarshalJSON(data []byte) error {
	inner := GetStuffListRequest{}
	err := json.Unmarshal(data, &inner)
	if err != nil {
		return err
	}
	if inner.Dt == nil {
		return errors.New("Dt cannot be nil")
	}

	if inner.St == nil {
		return errors.New("St cannot be nil")
	}

	if inner.Bt == nil {
		return errors.New("Bt cannot be nil")
	}

	*r = GetStuffListRequest{
		Dt: inner.Dt,
		St: inner.St,
		Bt: inner.Bt,
		It: inner.It,
	}
	return nil
}
```

This generated code is incorrect because:
1. It results in an infinite loop when unmarshalling, and
1. It's returning an error if an optional value is `nil`.

The correct approach is to:
1. Create a separate (inner) struct where all fields are pointers
1. Unmarshall into the inner struct
1. Check that required fields aren't `nil`
1. Construct a new target struct with the unmarshalled values from the inner struct.

See the issue description for a working example.

**Comment by springwiz** [comment]
Ok I should have caught this earlier but on second thoughts as far as I understand the change is intended to validate the incoming **post request body** which contains **nullable** fields(pointers in golang terms). But sysl as language doesn't support pointers all it has is aliases. These are all the types Sysl supports:
**decimal, int64, float64, string, bool, date, datetime and custom types defined within sysl**
So as both the endpoints and post request types are described in Sysl, the generated golang types couldn't have pointers as embedded data. For instance:
```
/stuff:
        POST (request <: PostRequest [~body]):
            return ok <: str

!type PostRequest:
        Dt <: datetime:
            @json_tag = "dt"
        St <: string:
            @json_tag = "st"
        Bt <: bool:
            @json_tag = "bt"
        response <: Response:
            @json_tag = "response"

!type Response:
        Data <: set of Item
```

Would **generate** the golang code as:-

```go
// PostStuffRequest ...
type PostStuffRequest struct {
	Request PostRequest
}

// PostRequest ...
type PostRequest struct {
	Bt       bool             `json:"Bt"`
	Dt       convert.JSONTime `json:"Dt"`
	St       string           `json:"St"`
	Response Response         `json:"response"`
}
```

**So you can't principally have an input post body as below**:
```go
// PostRequest ...
type PostRequest struct {
	Bt *bool             `json:"Bt"`
	Dt *convert.JSONTime `json:"Dt"`
	St *string           `json:"St"`
        Response *Response         `json:"response"`
} 
```
You can have nullable parameters as query params but they are already validated in the service handler plus they will never be json decoded which is the reason why the UnmarshalJSON implementation is not being called.
@andrewemeryanz thoughts on this.

**Comment by andrewemeryanz** [comment]
`sysl-go` does support the generation of optional `!type` fields.

The following specification:
```
!type Address:
    buildingName <: string?:
        @json_tag = "buildingName"
    streetNumber <: string:
        @json_tag = "streetNumber"
```

Generates the following `types.go`:
```go
// Address ...
type Address struct {
    BuildingName            *string                  `json:"buildingName,omitempty"`
    StreetNumber            string                   `json:"streetNumber"`
}
```

**Comment by springwiz** [comment]
Issue resolved as part of https://github.com/anz-bank/sysl-go/pull/153.
