### ISSUE TITLE
<critical> path var in endpoint does not get added to the client interface name, causes duplicate func names

### ISSUE THREAD

**Issue by ghost** [anz-bank/sysl-go#110]
sysl:
```
/orders/states:
        GET ?q=string?:
            | No description.
            return error
            return ok
/orders/{id<:int64}/states:
        GET ?q=string?&limit=int32?&offset=int32?:
            | No description.
            return error
            return ok <: OrderStateDto
```

Both of these endpoints generates a func named `GetOrdersStatesList(ctx context.Context, req *GetOrdersStatesListRequest) `, and both have the same named req type (which is also generated twice, once for each with different fields).

I think the required fix is that the second endpoint should take the path var names into account when naming, so something like `GetOrdersIdStatesList(...)` (which yeah, looks ugly but will have to do)

**Comment by anzdaddy** [comment]
Any solution to this needs to be opt-in. The example API is badly designed, and we shouldn't make every single API wear the cost of this.

**Comment by ghost** [comment]
Agreed, happy to add an attribute to the endpoint to work around this
