### ISSUE TITLE
Support integer query parameters in service handler

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl-go#121]
The generated `servicehandler` currently assumes all query parameters are strings.

The following endpoint:
```
/example/endpoint:
    GET (Request <: Data [~body]) ?name=string&taskId=int?:
        return ok <: Response
```

Generates a service handler that fails to compile when assigning a value to a request:
```go
req.Name = restlib.GetQueryParam(r, "name") // string parameter, correct
req.TaskId = restlib.GetQueryParam(r, "taskId") // integer parameter, incorrect
```

A correctly generated service handler should differentiate integer (and other) types correctly:
```go
req.Name = restlib.GetQueryParam(r, "name")
req.TaskId = restlib.GetQueryParamForInt(r, "taskId")
```

**Comment by springwiz** [comment]
The change is already taken care for upstream and convert package has methods for handling the conversion of the captured string query param to the appropriate data type. Is the fix required in downstream?

There are working examples in simple.sysl.
/stuff:
        GET ?dt=DATETIME?&st=string?&bt=bool?&it=int?:
            return ok <: Stuff
        POST (request <: str [~body]):
            return ok <: str

**Comment by andrewemeryanz** [comment]
> Is the fix required in downstream?

Yes, downstream services.

**Comment by springwiz** [comment]
Couldn't reproduce the issue
I tried adding a query param to downstream sysl as:
/service-docs:
        GET ?id=int?:
            | Return whole service docs
            return ok <: ServiceDoc
            return error <: status
and generated the code, it looks fine and compiles with data conversion in place in downstream servicehandler.go.

**Comment by springwiz** [comment]
Please delete service.go, servicehandler.go, types.go and then regenerate the code. Sometimes it doesn't generate the code even if there is a change in sysl, as the generated code is already present.

**Comment by andrewemeryanz** [comment]
> Yes, downstream services.

Ugh. Sorry. I've made a mistake. It's an upstream service. I'm actually generating a stub for a downstream service, hence the confusion.

The following specification:
```
Foo "Foo":
    @package = "foo"

    /rest/foo/{foo<:int}/bar/{bar<:int}:
        DELETE ?formId=string&caseId=int:
            return ok
```

With the following command:
```
sysl codegen --root-transform github.com/anz-bank/sysl-go/codegen@v0.31.0 --grammar grammars/go.gen.g --start goFile --basepath foo --app-name Foo --transform transforms/svc_handler.sysl specs/backend/foo.sysl
```

Generates the following:
```go
// DeleteRestFooBarHandler ...
func (s *ServiceHandler) DeleteRestFooBarHandler(w http.ResponseWriter, r *http.Request) {
	if s.serviceInterface.DeleteRestFooBar == nil {
		common.HandleError(r.Context(), w, common.InternalError, "not implemented", nil, s.genCallback.MapError)
		return
	}

	ctx := common.RequestHeaderToContext(r.Context(), r.Header)
	ctx = common.RespHeaderAndStatusToContext(ctx, make(http.Header), http.StatusOK)
	var req DeleteRestFooBarRequest

	req.Foo = restlib.GetURLParamForInt(r, "foo")
	req.Bar = restlib.GetURLParamForInt(r, "bar")
	req.FormId = restlib.GetQueryParam(r, "formId")
	req.CaseId = restlib.GetQueryParam(r, "caseId") // issue
	ctx, cancel := s.genCallback.DownstreamTimeoutContext(ctx)
	defer cancel()
	valErr := validator.Validate(&req)
	if valErr != nil {
		common.HandleError(ctx, w, common.BadRequestError, "Invalid request", valErr, s.genCallback.MapError)
		return
	}

	client := DeleteRestFooBarClient{}

	err := s.serviceInterface.DeleteRestFooBar(ctx, &req, client)
	if err != nil {
		common.HandleError(ctx, w, common.DownstreamUnexpectedResponseError, "Downstream failure", err, s.genCallback.MapError)
		return
	}

	headermap, httpstatus := common.RespHeaderAndStatusFromContext(ctx)
	restlib.SetHeaders(w, headermap)
	restlib.SendHTTPResponse(w, httpstatus, nil)
}
```

**Comment by andrewemeryanz** [comment]
Upon further investigation, the issue only affects `int` query parameters, not `int?`:
```
Foo "Foo":
    @package = "foo"

    /rest/foo/{foo<:int}/bar/{bar<:int}:
        DELETE ?formId=string&caseId=int?: # correctly generated
            return ok

    /rest/baz/{foo<:int}/bar/{bar<:int}:
        DELETE ?formId=string&caseId=int: # incorrectly generated
            return ok
```

**Comment by springwiz** [comment]
In your usecase not using "?" doesn't make sense, as all query params are optional. But the sysl is still valid, and probably codegen should complain instead of generating non compiling code. Will check if I can do something about compilation issue.

**Comment by springwiz** [comment]
Arrai transforms need to be fixed as well.

**Comment by andrewemeryanz** [comment]
@springwiz Can you close this ticket and instead create a separate ticket to identify all gaps between `sysl` transforms and `arrai` transforms.

**Comment by springwiz** [comment]
ok
