### ISSUE TITLE
Identify and resolve gaps between `sysl` transforms and `arrai` transforms.

### ISSUE THREAD

**Issue by springwiz** [anz-bank/sysl-go#133]
@springwiz Can you close this ticket and instead create a separate ticket to identify all gaps between `sysl` transforms and `arrai` transforms.

_Originally posted by @andrewemeryanz in https://github.com/anz-bank/sysl-go/issues/121#issuecomment-647253848_

**Comment by andrewemeryanz** [comment]
@springwiz I'll attempt to migrate the first service to get a benchmark of code comparison. I'll then hand this over to you to investigate the remaining services.

**Comment by ghost** [comment]
@andrewemeryanz you probably want to check on my changes in https://github.service.anz/dcx/anzapp-bff/tree/master/codegen/arrai asI've already fixed a bunch of issues with the rest code

**Comment by andrewemeryanz** [comment]
@anz-gordonj7 Thanks.

**Comment by springwiz** [comment]
@anz-gordonj7 Can you point me to issues that you have fixed, in the arrai code included in dcx/anzapp-bff.

**Comment by ghost** [comment]
diff the dcx/codegen/arrai directory with sysl-go/codegen/arrai. I don't have a list of changes made

**Comment by andrewemeryanz** [comment]
Migration complete.
