### ISSUE TITLE
Update sysl-template

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl-go#155]
Update [sysl-template](https://github.com/anz-bank/sysl-template) to showcase more features of `sysl-go`.

Including:
- [x] Add sysl and arrai wrappers
- [x] Update `sysl` and `sysl-go` versions
- [x] Use openapi specification for service definition: Pet Pics (described below)
- [x] Use two downstream services: [Flickr](https://github.com/flickr/flickr-api-swagger/blob/ebdd68a37740ea2847b36e78e6fcb5a0b48b699e/schema.json) and [Petstore](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.json)
- [x] Use arrai for code generation
- [x] Update sysl-catalog generated pages

Pet Pics:
GET /random-pet-pic
1. Get all pets from the Petstore.
1. Select a random pet from the returned list.
1. Perform a `/rest?method=flickr.photos.search` search that passes through `tags`: `pet` and the name of the random pet.
1. Return a result that includes the pet name and the list of image urls.

**Comment by springwiz** [comment]
PR https://github.com/anz-bank/sysl-template/pull/9 merged.
