### ISSUE TITLE
Make json validate optional/configurable.

### ISSUE THREAD

**Issue by springwiz** [anz-bank/sysl-go#182]
Allow sysl-go adoption teams to opt out of json validation of sysl types.

**Comment by anzdaddy** [comment]
@springwiz What does "json validation of sysl types" mean, exactly?

**Comment by springwiz** [comment]
@anzdaddy We have recently introduced a feature wherein we validate the presence of a value in the mandatory fields of the sysl types when used in a request body. bah-bff team still don't mark all the field types as optional even though they don't pass a value. The feature breaks their build pipeline when migrated to arrai based code generation.

**Comment by anzdaddy** [comment]
Is it a lot of work to add the optional qualifier?

**Comment by springwiz** [comment]
Not really, just a few tweaks in the transform.
