### ISSUE TITLE
Remove static go file

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl-go#21]
[This file](https://github.com/anz-bank/sysl-go/tree/master/core/build) is causing issues with cloud build, 
and theoretically can be replaces with  [go redoc](https://github.com/go-openapi/runtime/blob/master/middleware/redoc.go)

**Comment by anzdaddy** [comment]
That file is 10x bigger than it needs to be. How is it generated?

**Comment by anzdaddy** [comment]
Elements of a good resource injection tool:
1. Supports http.FileSystem.
2. Compresses everything with max compression by default.
3. Uses string syntax to represent data in source code (much more compact than `[]byte{0x...}`).
4. Can serve gzip encoding directly to http clients without going through a decompression step.
