### ISSUE TITLE
Integrate new listener code into autogen

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl-go#211]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Purpose
> Please describe the _end goal_ you are trying to achieve that has led you to request this feature.

Currently, autogen runs a simple insecure listener. Integrate it with the sysl-go library code that builds a rich configurable listener.

### Suggested approaches
> What have you tried, and how might this problem be solved?

**Comment by andrewemeryanz** [comment]
Implemented.
