### ISSUE TITLE
Upgrade the validator package to v10

### ISSUE THREAD

**Issue by kasunSF** [anz-bank/sysl-go#229]
### Purpose
> Please describe the _end goal_ you are trying to achieve that has led you to request this feature.

Currently, the [validator](https://github.com/anz-bank/sysl-go/blob/master/validator/validator.go#L8) is using v9 version.
I would suggest using v10 since it has more features.

To be more specific, the [v10](https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-One_Of) validator allows the `oneof` validation to have the string with spaces which is handy for validating enum fields with space-separated enums.
```
Usage: oneof=red green
       oneof='red green' 'blue yellow'
       oneof=5 7 9
```

### Suggested approaches
> What have you tried, and how might this problem be solved?

**Comment by AriehSchneier** [comment]
This has now been done

**Comment by kasunSF** [comment]
Thank you @AriehSchneier 

Verified and worked.
