### ISSUE TITLE
Hide config types from custom code

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl-go#3]
Configuration for `sysl-go` is managed with the following process:
1. Create a `config.yaml` file that contains:
a. The `library` section for `sysl-go` library config
b. The `genCode` section for generated code configuration
c. Other sections read by custom code as required. 
2. Create a `Config` struct (in custom code) that contains yaml tags for the above sections.
3. Read the `config.yaml` file into the `Config` struct.
4. Use the `Config` internally.

The goal of this piece of work is to eliminate step 3 (above) by moving (into `sysl-go`) or generating (using `sysl-go` generators) as much of the configuration as possible.

The eventual goal of this work is to simplify the starting of a server to a command similar to the one below, where custom code knows only about its own configuration:

```go
gen.StartServer(
    func(ctx context.Context, config MyConfig) (foo.ServiceInterface, foo.GenCallback) {
        ...
    }
)
```

The above approach requires that `sysl-go` know how custom code provides the location of the configuration file. The config file should eventually be retrieved from the `config` argument on the command-line, however, to break this work into stages, the first step would be to provide a function that reads from a single config file and populates both custom and library config structs:

```go
func ReadConfig(file string, custom *interface{}) (common.Library, common.GenCode)
```
With usage:
```go
config := MyConfig{}
lib, gen := common.ReadConfig(file, &config)
```

**Comment by gkanz** [comment]
The configuration passed back to the custom code should be specific to the custom code. `sysl-go` should swallow all the config that is specific to it only.

**Comment by ChloePlanet** [comment]
Since `handlers`([#L17](https://github.com/anzx/bah-bff/blob/master/config.yaml#L17)) and `param`([#L30](https://github.com/anzx/bah-bff/blob/master/config.yaml#L30)) are actually part of custom config (I've confirmed it with bah-bff team), not configuration for generated code, I'd strip it out from `genCode`.

**Comment by ChloePlanet** [comment]
How about generating a `config.yaml` template under root path when generating go code?

**Comment by ChloePlanet** [comment]
@andrewemeryanz I'm considering splitting configuration for `sysl-go` in two aspects:
1. For code generation:
    1. Generate a `config.yaml` template that contains:
        a. The `library` section for `sysl-go` library config
        b. The `genCode` section for generated code configuration
    2. Generate code which including:
        a. `Config` struct that contains fields and yaml tags for the above sections.
        b. Read the `config.yaml` file into the `Config` struct.
        c. Use the `Config` internally (in `LoadServices` probably).
2. For our users (if they need custom configuration):
    1. Add other custom sections read by custom code as required in `config.yaml`
    2. Create a `MyConfig` struct (in custom code) that contains yaml tags for the above sections.
    3. Read the `config.yaml` file into the `MyConfig` struct.
    4. Use the `MyConfig` in custom code.
    (For the last two steps, is there a way to know user's `MyConfig` structure? Or we just require the custom config struct name has to be `MyConfig` )

**Comment by ChloePlanet** [comment]
From Gregg:
`library`, `server`, and `genCode/upstream` is static. `genCode/downstream` will need codgen to know things like how many downstreams there are and what they are called etc.
