### ISSUE TITLE
Investigate updating to Go 1.14

### ISSUE THREAD

**Issue by cuminandpaprika** [anz-bank/sysl-go#34]
As discussed [here](https://github.com/anz-bank/sysl-go/pull/23#discussion_r395388078), need to check the compatibility issues.

Perhaps building and testing using several versions of Go in CI may be a good way to extend our support for various Go versions

**Comment by gkanz** [comment]
I'd like sysl-go to use 1.14, and we can upgrade sysl to the same. If there are compabability issues we will deal with them. #56
