### ISSUE TITLE
Support 'oneof' keyword in OpenApi to specify schemas of API response for sysl code generation

### ISSUE THREAD

**Issue by linwumeng** [anz-bank/sysl-go#95]
Sysl code generation doesn't support 'oneof' keyword in OpenApi.
```
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
```
Request new feature of sysl to generate code of bff and clients from OpenApi specs supporting 'oneof'.

**Comment by anzdaddy** [comment]
As a quick workaround, we'll expose the request directly to the handler in the case that the top level thing is a oneof.

**Comment by linwumeng** [comment]
Take https://github.com/anz-bank/sysl-go/blob/master/codegen/tests/simple/servicehandler.go as example. The generated code is
```
type Handler interface {
	GetApiDocsListHandler(w http.ResponseWriter, r *http.Request)
	... 
}
type ServiceHandler struct {
	genCallback                 core.RestGenCallback
	serviceInterface            *ServiceInterface
	depsDepsService             deps.Service
	downstreamDownstreamService downstream.Service
}
func (s *ServiceHandler) GetApiDocsListHandler(w http.ResponseWriter, r *http.Request) {
	...
	apidoc, err := s.serviceInterface.GetApiDocsList(ctx, &req, client)
	if err != nil {
		common.HandleError(ctx, w, common.DownstreamUnexpectedResponseError, "Downstream failure", err, s.genCallback.MapError)
		return
	}

	headermap, httpstatus := common.RespHeaderAndStatusFromContext(ctx)
	restlib.SetHeaders(w, headermap)
	restlib.SendHTTPResponse(w, httpstatus, apidoc)
}
```
It works well when the schema of response body is a certain one instead of 'oneOf'. In this case, `apidoc` at `apidoc, err := s.serviceInterface.GetApiDocsList(ctx, &req, client)`  is of `*[]deps.ApiDoc`.
For `oneOf`, will `apidoc` be of `interface{}` as a workround?

**Comment by ghost** [comment]
@anzdaddy Any updates on this please? Its going to be blocking us very soon

**Comment by andrewemeryanz** [comment]
@anz-gordonj7 Issue will be picked up within the next day or two.

**Comment by tiagralee** [comment]
@linwumeng @anz-gordonj7 @anzdaddy Need a bit more information of what should be the expected result  of the codegen, an example of the input and output would be good. Not every clear how the transform takes the OpenApi specs and read the `oneOf` keyword. Any background or information would be helpful, thanks.

**Comment by ghost** [comment]
`oneOf` is not supported by the swagger importer yet so that is a seperate issue that can be done in parallel (probably by me).

I would expect that it would generate a sysl `!union` type, which would turn into a 
```
type foo struct   {
   other *Other
   something *Something
}
```

the codegen would then have to try to `json.(un)Marshal` each of the fields and succeed on the first one that works?

**Comment by tiagralee** [comment]
> `oneOf` is not supported by the swagger importer yet so that is a seperate issue that can be done in parallel (probably by me).
> 
> I would expect that it would generate a sysl `!union` type, which would turn into a
> 
> ```
> type foo struct   {
>    other *Other
>    something *Something
> }
> ```
> 
> the codegen would then have to try to `json.(un)Marshal` each of the fields and succeed on the first one that works?

@anz-gordonj7 correct me if I'm wrong, 
the input for code gen will be
```
!union foo:
    Other
    Something

/foo:
    GET
          return of <: foo
```
the transform would then generate
```
type foo struct   {
   other *Other
   something *Something
}
```
service handler and service client do the json.(un)Marshal?

**Comment by ghost** [comment]
@tiagralee correct

**Comment by tiagralee** [comment]
Hi @anz-gordonj7 @linwumeng @andrewemeryanz , I did a `json.unMarshal` test, and noticed that if the two union type have some shared fields, like one in extend another, while we use the looped approach to unmarshal, both will work, so we might have some type mismatch.
Like below
```
!union Pet
       Cat
       Dog
```
```
type Dog struct {
    Name   string
    Age      int
}

type Cat struct {
    Name   string
    Age      int
    Color   string
}
```
if we have input
```
str := `{"Name": "something", "Age": 2, "Color": "black"}`
```
both `Cat` and `Dog` can be UnMarshal successfully.
Is it possible that we can include an identifier in sysl while import the swagger or do you have any other suggestions?
In OpenAPI specification we can use `discriminator` along with `oneof`
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject

**Comment by linwumeng** [comment]
@tiagralee , thanks for your advice. You are correct. the specs in our case looks like
```
components:
  schemas:
    Pet:
      type: object
      required:
      - petType
      properties:
        petType:
          type: string
      discriminator:
        propertyName: petType
        mapping:
          dog: Dog
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string
    Lizard:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Lizard`
        properties:
          lovesRocks:
            type: boolean
```

**Comment by orlade-anz** [comment]
@cuminandpaprika is working on fixing the importer to support `oneOf` statements, and I'll look at the codegen to turn that into Go.

**Comment by JackLeeHal** [comment]
Thanks @cuminandpaprika @orlade-anz. Currently, we are using our own arrai transform in our project. So once you fix it we might need to take a look and migrate to our own repo.

**Comment by orlade-anz** [comment]
Related: https://github.com/anz-bank/sysl/issues/976

**Comment by cuminandpaprika** [comment]
Basic support for the OneOf syntax in the OpenAPI Importer added in https://github.com/anz-bank/sysl/pull/997

**Comment by ericzhang6222** [comment]
Fixed by https://github.com/anz-bank/sysl-go/pull/198
